title: "OctaPi: Calculate Pi"
hero_image: images/banner.png
description: Learn how to calculate Pi using the power of distributed computing
theme: cc-prototype
duration: 3 # 1, 2 or 3
listed: false
ingredient: false
interests: ""
technologies: "python"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step one - Why is calculating π difficult?
  - title: Step two - Calculating π - Viète's method
  - title: Step three - Representing decimals on a computer
  - title: Step four - Monte Carlo methods
  - title: Step five - Implementing the 'dartboard' algorithm on a single standalone processor
  - title: Step six - Comparing the two methods
  - title: Step seven - Implementing the 'dartboard' algorithm on a distributed system
  - title: Challenge
